### ISSUE TITLE
Why is there no release?

### ISSUE THREAD

**Issue by SeanTolstoyevski** [NicklasTegner/UtopiaForReddit#1]
Hello Nick,

Are you considering adding README and preparing installable files **(release files)**?

**Comment by NicklasTegner** [comment]
hi @SeanTolstoyevski 
Yes, I am planning a release, however I have just had some problems with travis-ci (which I use to build releases for my programs).
I'll work on it and report back here, when I have a solution.
Thanks for showing interest

**Comment by NicklasTegner** [comment]
Hi @SeanTolstoyevski 
THe repository has been set up for an eventual release down the line, however the codebase are not ready for a "stable" release yet.
I'll close this issue, since a release will be coming out, when the code is more mature.
